### PR TITLE
Adding examples

### PR DESCRIPTION
**Pull request by OskarKlintrot**
Thanks for this amazing tool, it really is a joy not to have to spend hours and hours just to set up a build process! I have two examples, one for the server and one for the client. If they run both at the same time the client will fetch data from the server. I haven't added any tests yet though. Feel free to add them if you want or just merge this as is. I will try to write the tests anyway but I don't really have the time right now. But maybe next week. Also the React app might not be of the highest quality (I'm really rusty after spending the last half year in C#.NET) but it works, feel free to do whatever you want with it, I guess you have your own best practices for how to work with React.

## Features

- [x] Server example with Express
- [x] Client example with React
- [x] Examples can communicate between them
- [ ] Client has unit tests
- [ ] Server has unit tests

### CODE REVIEW

**Comment by Pajn** [comment]
This is great, thanks!

I just wounder about the two images. What is the license on them? Are we allowed to redistribute them? Do we need to give attribution?

**Comment by OskarKlintrot** [comment]
That's a good question, they are coming from [Unsplash](https://unsplash.com/) and has the license CC Zero, which mean anyone can do whatever they want with them. I added some info about the license for the images to the PR.

**Comment by Pajn** [comment]
Super! Thank you!

**Comment by OskarKlintrot** [comment]
Thanks! I did a new PR where I tweaked to CSS a bit, I just couldn't stand the half-finished look 😄

**Pull request merged**
